image: riconet/gitlab-ci-pipeline-php:8.0-alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - vendor/
  - public/

stages:
  - Build
  - Deploy

build:
   stage: Build
   image: composer:2.3
   script:
      - composer install --ignore-platform-reqs --optimize-autoloader --prefer-dist --no-progress

deploy:
  stage: Build
  script:
    - echo 'TODO'
